# syntax=docker/dockerfile:1

FROM node:22-alpine

WORKDIR /src/app/

ENV POKEMON_SERVICE_URL=0.0.0.0:3001

COPY ./vite.config.ts /src/app/vite.config.ts
COPY ./tsconfig.json /src/app/tsconfig.json
COPY ./package.json /src/app/package.json
COPY ./public/ /src/app/public/
COPY ./app/ /src/app/app/

RUN npm install --omit=dev

RUN npm run build

CMD npm run start

EXPOSE 3000
